export type IngredientCategory =
  | 'protein' | 'carb' | 'veg' | 'fruit' | 'dairy' | 'fat' | 'drink' | 'snack' | 'condiment'

export interface IngredientUnit {
  name: string   // singular natural unit, e.g. 'egg', 'slice', 'tbsp', 'scoop', 'cup'
  grams: number  // gram weight of one unit (for liquids: ml, treated 1:1 with grams)
}

export interface LibraryIngredient {
  id: string                 // stable kebab-case slug, unique, e.g. 'chicken-breast-raw'
  name: string               // display name, e.g. 'Chicken breast (raw)'
  category: IngredientCategory
  emoji: string              // one emoji for the row icon
  aliases?: string[]         // lowercase search aliases (common alternate names)
  per100: { cal: number; protein: number; carbs: number }  // per 100 g (liquids: per 100 ml)
  units?: IngredientUnit[]   // natural portion units, most common FIRST
  liquid?: boolean           // true → measured in ml
  hydrating?: boolean        // liquid counts toward water intake (water, juice, milk...; NOT beer/wine/liquor)
  caffeinePer100?: number    // mg caffeine per 100 ml (coffee, tea, energy drinks, cola)
}

export const INGREDIENT_LIBRARY: LibraryIngredient[] = [
  // ── protein ──
  { id: 'bacon-cooked', name: 'Bacon (cooked)', category: 'protein', emoji: '🥓', per100: { cal: 541, protein: 37.0, carbs: 1.4 }, units: [{ name: 'slice', grams: 10 }] },
  { id: 'beef-jerky', name: 'Beef jerky', category: 'protein', emoji: '🥩', aliases: ['jerky'], per100: { cal: 410, protein: 33.2, carbs: 11.0 }, units: [{ name: 'oz', grams: 28 }, { name: 'piece', grams: 7 }] },
  { id: 'casein-protein', name: 'Casein protein powder', category: 'protein', emoji: '🥤', aliases: ['casein'], per100: { cal: 360, protein: 72.0, carbs: 9.0 }, units: [{ name: 'scoop', grams: 33 }] },
  { id: 'chicken-breast-cooked', name: 'Chicken breast (cooked)', category: 'protein', emoji: '🍗', aliases: ['grilled chicken'], per100: { cal: 165, protein: 31.0, carbs: 0 }, units: [{ name: 'breast', grams: 150 }, { name: 'oz', grams: 28 }] },
  { id: 'chicken-breast-raw', name: 'Chicken breast (raw)', category: 'protein', emoji: '🍗', per100: { cal: 120, protein: 22.5, carbs: 0 }, units: [{ name: 'breast', grams: 200 }, { name: 'oz', grams: 28 }] },
  { id: 'chicken-drumstick-cooked', name: 'Chicken drumstick (cooked)', category: 'protein', emoji: '🍗', aliases: ['drumstick'], per100: { cal: 216, protein: 27.0, carbs: 0 }, units: [{ name: 'drumstick', grams: 72 }] },
  { id: 'chicken-thigh-cooked', name: 'Chicken thigh (cooked)', category: 'protein', emoji: '🍗', per100: { cal: 209, protein: 26.0, carbs: 0 }, units: [{ name: 'thigh', grams: 85 }, { name: 'oz', grams: 28 }] },
  { id: 'chicken-thigh-raw', name: 'Chicken thigh (raw)', category: 'protein', emoji: '🍗', per100: { cal: 121, protein: 19.7, carbs: 0 }, units: [{ name: 'thigh', grams: 120 }, { name: 'oz', grams: 28 }] },
  { id: 'cod-cooked', name: 'Cod (cooked)', category: 'protein', emoji: '🐟', per100: { cal: 105, protein: 22.8, carbs: 0 }, units: [{ name: 'fillet', grams: 140 }, { name: 'oz', grams: 28 }] },
  { id: 'deli-ham', name: 'Deli ham', category: 'protein', emoji: '🍖', aliases: ['ham', 'sliced ham'], per100: { cal: 107, protein: 16.6, carbs: 1.5 }, units: [{ name: 'slice', grams: 28 }] },
  { id: 'deli-roast-beef', name: 'Deli roast beef', category: 'protein', emoji: '🥩', aliases: ['roast beef'], per100: { cal: 115, protein: 18.6, carbs: 0.6 }, units: [{ name: 'slice', grams: 28 }] },
  { id: 'deli-turkey', name: 'Deli turkey', category: 'protein', emoji: '🦃', aliases: ['sliced turkey', 'turkey cold cuts'], per100: { cal: 104, protein: 17.0, carbs: 3.5 }, units: [{ name: 'slice', grams: 28 }] },
  { id: 'egg', name: 'Egg (whole)', category: 'protein', emoji: '🥚', aliases: ['eggs', 'whole egg'], per100: { cal: 143, protein: 12.6, carbs: 0.7 }, units: [{ name: 'egg', grams: 50 }] },
  { id: 'egg-whites', name: 'Egg whites', category: 'protein', emoji: '🥚', aliases: ['egg white', 'liquid egg whites'], per100: { cal: 52, protein: 10.9, carbs: 0.7 }, units: [{ name: 'egg white', grams: 33 }, { name: 'cup', grams: 243 }] },
  { id: 'flank-steak-cooked', name: 'Flank steak (cooked)', category: 'protein', emoji: '🥩', per100: { cal: 194, protein: 28.0, carbs: 0 }, units: [{ name: 'oz', grams: 28 }, { name: 'serving', grams: 170 }] },
  { id: 'ground-beef-80-cooked', name: 'Ground beef 80/20 (cooked)', category: 'protein', emoji: '🥩', per100: { cal: 272, protein: 25.8, carbs: 0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'ground-beef-80-raw', name: 'Ground beef 80/20 (raw)', category: 'protein', emoji: '🥩', aliases: ['80/20'], per100: { cal: 254, protein: 17.2, carbs: 0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'ground-beef-90-raw', name: 'Ground beef 90/10 (raw)', category: 'protein', emoji: '🥩', aliases: ['90/10'], per100: { cal: 176, protein: 20.0, carbs: 0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'ground-beef-93-cooked', name: 'Ground beef 93/7 (cooked)', category: 'protein', emoji: '🥩', per100: { cal: 190, protein: 25.6, carbs: 0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'ground-beef-93-raw', name: 'Ground beef 93/7 (raw)', category: 'protein', emoji: '🥩', aliases: ['93/7'], per100: { cal: 152, protein: 20.9, carbs: 0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'ground-beef-96-raw', name: 'Ground beef 96/4 (raw)', category: 'protein', emoji: '🥩', aliases: ['96/4', 'extra lean ground beef'], per100: { cal: 130, protein: 21.7, carbs: 0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'ground-chicken-raw', name: 'Ground chicken (raw)', category: 'protein', emoji: '🍗', per100: { cal: 143, protein: 17.4, carbs: 0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'ground-pork-raw', name: 'Ground pork (raw)', category: 'protein', emoji: '🐖', per100: { cal: 263, protein: 16.9, carbs: 0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'ground-turkey-93-raw', name: 'Ground turkey 93/7 (raw)', category: 'protein', emoji: '🦃', aliases: ['ground turkey'], per100: { cal: 150, protein: 18.7, carbs: 0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'italian-sausage-cooked', name: 'Italian sausage (cooked)', category: 'protein', emoji: '🌭', per100: { cal: 344, protein: 19.1, carbs: 4.3 }, units: [{ name: 'link', grams: 83 }] },
  { id: 'lamb-cooked', name: 'Lamb (cooked)', category: 'protein', emoji: '🍖', aliases: ['ground lamb', 'lamb chop'], per100: { cal: 283, protein: 24.8, carbs: 0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'pork-chop-cooked', name: 'Pork chop (cooked)', category: 'protein', emoji: '🐖', per100: { cal: 214, protein: 27.5, carbs: 0 }, units: [{ name: 'chop', grams: 130 }, { name: 'oz', grams: 28 }] },
  { id: 'pork-sausage-cooked', name: 'Pork sausage (cooked)', category: 'protein', emoji: '🌭', aliases: ['breakfast sausage', 'sausage'], per100: { cal: 325, protein: 18.5, carbs: 1.4 }, units: [{ name: 'link', grams: 25 }, { name: 'patty', grams: 35 }] },
  { id: 'pork-tenderloin-cooked', name: 'Pork tenderloin (cooked)', category: 'protein', emoji: '🐖', per100: { cal: 143, protein: 26.2, carbs: 0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'ribeye-steak-cooked', name: 'Ribeye steak (cooked)', category: 'protein', emoji: '🥩', aliases: ['ribeye'], per100: { cal: 291, protein: 24.8, carbs: 0 }, units: [{ name: 'oz', grams: 28 }, { name: 'steak', grams: 250 }] },
  { id: 'rotisserie-chicken', name: 'Rotisserie chicken (meat + skin)', category: 'protein', emoji: '🍗', per100: { cal: 215, protein: 25.0, carbs: 0 }, units: [{ name: 'oz', grams: 28 }, { name: 'cup', grams: 140 }] },
  { id: 'salmon-cooked', name: 'Salmon (cooked)', category: 'protein', emoji: '🐟', per100: { cal: 206, protein: 22.1, carbs: 0 }, units: [{ name: 'fillet', grams: 150 }, { name: 'oz', grams: 28 }] },
  { id: 'salmon-raw', name: 'Salmon (raw)', category: 'protein', emoji: '🐟', per100: { cal: 208, protein: 20.4, carbs: 0 }, units: [{ name: 'fillet', grams: 170 }, { name: 'oz', grams: 28 }] },
  { id: 'sardines-canned', name: 'Sardines (canned in oil)', category: 'protein', emoji: '🐟', aliases: ['sardines'], per100: { cal: 208, protein: 24.6, carbs: 0 }, units: [{ name: 'can', grams: 92 }] },
  { id: 'shrimp-cooked', name: 'Shrimp (cooked)', category: 'protein', emoji: '🍤', aliases: ['prawns'], per100: { cal: 99, protein: 24.0, carbs: 0.2 }, units: [{ name: 'shrimp', grams: 8 }, { name: 'oz', grams: 28 }] },
  { id: 'sirloin-steak-cooked', name: 'Sirloin steak (cooked)', category: 'protein', emoji: '🥩', aliases: ['sirloin', 'steak'], per100: { cal: 206, protein: 29.0, carbs: 0 }, units: [{ name: 'oz', grams: 28 }, { name: 'steak', grams: 225 }] },
  { id: 'smoked-salmon', name: 'Smoked salmon', category: 'protein', emoji: '🍣', aliases: ['lox'], per100: { cal: 117, protein: 18.3, carbs: 0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'tempeh', name: 'Tempeh', category: 'protein', emoji: '🌱', per100: { cal: 192, protein: 20.3, carbs: 7.6 }, units: [{ name: 'cup', grams: 166 }, { name: 'oz', grams: 28 }] },
  { id: 'tilapia-cooked', name: 'Tilapia (cooked)', category: 'protein', emoji: '🐟', per100: { cal: 128, protein: 26.2, carbs: 0 }, units: [{ name: 'fillet', grams: 90 }, { name: 'oz', grams: 28 }] },
  { id: 'tofu-firm', name: 'Tofu (firm)', category: 'protein', emoji: '🌱', aliases: ['tofu'], per100: { cal: 94, protein: 10.6, carbs: 2.3 }, units: [{ name: 'serving', grams: 85 }, { name: 'block', grams: 396 }] },
  { id: 'tuna-canned-water', name: 'Tuna (canned in water)', category: 'protein', emoji: '🐟', aliases: ['canned tuna', 'tuna'], per100: { cal: 116, protein: 25.5, carbs: 0 }, units: [{ name: 'can', grams: 113 }] },
  { id: 'turkey-bacon-cooked', name: 'Turkey bacon (cooked)', category: 'protein', emoji: '🥓', per100: { cal: 382, protein: 29.5, carbs: 3.1 }, units: [{ name: 'slice', grams: 8 }] },
  { id: 'turkey-breast-cooked', name: 'Turkey breast (cooked)', category: 'protein', emoji: '🦃', per100: { cal: 135, protein: 30.0, carbs: 0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'whey-protein', name: 'Whey protein powder', category: 'protein', emoji: '🥤', aliases: ['protein powder', 'whey'], per100: { cal: 400, protein: 80.0, carbs: 10.0 }, units: [{ name: 'scoop', grams: 30 }] },

  // ── carb ──
  { id: 'bagel', name: 'Bagel (plain)', category: 'carb', emoji: '🥯', per100: { cal: 257, protein: 10.2, carbs: 50.9 }, units: [{ name: 'bagel', grams: 105 }, { name: 'half bagel', grams: 53 }] },
  { id: 'black-beans-cooked', name: 'Black beans (cooked)', category: 'carb', emoji: '🫘', aliases: ['black beans'], per100: { cal: 132, protein: 8.9, carbs: 23.7 }, units: [{ name: 'cup', grams: 172 }] },
  { id: 'bread-sourdough', name: 'Bread (sourdough)', category: 'carb', emoji: '🍞', aliases: ['sourdough'], per100: { cal: 272, protein: 10.8, carbs: 53.6 }, units: [{ name: 'slice', grams: 50 }] },
  { id: 'bread-white', name: 'Bread (white)', category: 'carb', emoji: '🍞', aliases: ['white bread', 'toast'], per100: { cal: 266, protein: 8.9, carbs: 49.2 }, units: [{ name: 'slice', grams: 40 }] },
  { id: 'bread-whole-wheat', name: 'Bread (whole wheat)', category: 'carb', emoji: '🍞', aliases: ['wheat bread', 'whole grain bread'], per100: { cal: 252, protein: 12.3, carbs: 42.7 }, units: [{ name: 'slice', grams: 40 }] },
  { id: 'brown-rice-cooked', name: 'Brown rice (cooked)', category: 'carb', emoji: '🍚', per100: { cal: 123, protein: 2.7, carbs: 25.6 }, units: [{ name: 'cup', grams: 195 }] },
  { id: 'brown-rice-dry', name: 'Brown rice (dry)', category: 'carb', emoji: '🍚', per100: { cal: 370, protein: 7.9, carbs: 77.2 }, units: [{ name: 'cup', grams: 185 }] },
  { id: 'cereal-corn-flakes', name: 'Cereal (corn flakes)', category: 'carb', emoji: '🥣', aliases: ['corn flakes', 'cereal'], per100: { cal: 357, protein: 7.5, carbs: 84.1 }, units: [{ name: 'cup', grams: 28 }] },
  { id: 'chickpeas-canned', name: 'Chickpeas (canned)', category: 'carb', emoji: '🫘', aliases: ['garbanzo beans'], per100: { cal: 139, protein: 7.0, carbs: 22.5 }, units: [{ name: 'cup', grams: 152 }] },
  { id: 'couscous-cooked', name: 'Couscous (cooked)', category: 'carb', emoji: '🍚', per100: { cal: 112, protein: 3.8, carbs: 23.2 }, units: [{ name: 'cup', grams: 157 }] },
  { id: 'crackers-saltine', name: 'Crackers (saltine)', category: 'carb', emoji: '🍘', aliases: ['saltines'], per100: { cal: 421, protein: 9.0, carbs: 74.3 }, units: [{ name: 'cracker', grams: 3 }] },
  { id: 'cream-of-rice-dry', name: 'Cream of rice (dry)', category: 'carb', emoji: '🥣', aliases: ['rice cereal'], per100: { cal: 370, protein: 6.5, carbs: 83.0 }, units: [{ name: 'serving', grams: 45 }] },
  { id: 'croissant', name: 'Croissant', category: 'carb', emoji: '🥐', per100: { cal: 406, protein: 8.2, carbs: 45.8 }, units: [{ name: 'croissant', grams: 57 }] },
  { id: 'egg-noodles-cooked', name: 'Egg noodles (cooked)', category: 'carb', emoji: '🍜', per100: { cal: 138, protein: 4.5, carbs: 25.2 }, units: [{ name: 'cup', grams: 160 }] },
  { id: 'english-muffin', name: 'English muffin', category: 'carb', emoji: '🍞', per100: { cal: 235, protein: 7.7, carbs: 46.0 }, units: [{ name: 'muffin', grams: 57 }] },
  { id: 'french-fries', name: 'French fries', category: 'carb', emoji: '🍟', aliases: ['fries'], per100: { cal: 312, protein: 3.4, carbs: 41.4 }, units: [{ name: 'medium serving', grams: 115 }, { name: 'large serving', grams: 155 }] },
  { id: 'granola', name: 'Granola', category: 'carb', emoji: '🥣', per100: { cal: 471, protein: 10.5, carbs: 64.5 }, units: [{ name: 'half cup', grams: 61 }, { name: 'cup', grams: 122 }] },
  { id: 'hamburger-bun', name: 'Hamburger bun', category: 'carb', emoji: '🍔', aliases: ['burger bun', 'bun'], per100: { cal: 279, protein: 9.7, carbs: 50.1 }, units: [{ name: 'bun', grams: 50 }] },
  { id: 'instant-ramen-dry', name: 'Instant ramen (dry)', category: 'carb', emoji: '🍜', aliases: ['ramen'], per100: { cal: 440, protein: 9.4, carbs: 63.0 }, units: [{ name: 'pack', grams: 85 }] },
  { id: 'kidney-beans-cooked', name: 'Kidney beans (cooked)', category: 'carb', emoji: '🫘', per100: { cal: 127, protein: 8.7, carbs: 22.8 }, units: [{ name: 'cup', grams: 177 }] },
  { id: 'lentils-cooked', name: 'Lentils (cooked)', category: 'carb', emoji: '🫘', per100: { cal: 116, protein: 9.0, carbs: 20.1 }, units: [{ name: 'cup', grams: 198 }] },
  { id: 'mashed-potatoes', name: 'Mashed potatoes', category: 'carb', emoji: '🥔', per100: { cal: 113, protein: 2.0, carbs: 16.8 }, units: [{ name: 'cup', grams: 210 }] },
  { id: 'naan', name: 'Naan', category: 'carb', emoji: '🫓', per100: { cal: 291, protein: 8.7, carbs: 50.4 }, units: [{ name: 'piece', grams: 90 }] },
  { id: 'oatmeal-cooked', name: 'Oatmeal (cooked)', category: 'carb', emoji: '🥣', aliases: ['porridge'], per100: { cal: 71, protein: 2.5, carbs: 12.0 }, units: [{ name: 'cup', grams: 234 }] },
  { id: 'oats-dry', name: 'Oats (dry)', category: 'carb', emoji: '🥣', aliases: ['oatmeal', 'rolled oats'], per100: { cal: 379, protein: 13.2, carbs: 67.7 }, units: [{ name: 'half cup', grams: 40 }, { name: 'cup', grams: 81 }] },
  { id: 'pancake', name: 'Pancake', category: 'carb', emoji: '🥞', per100: { cal: 227, protein: 6.4, carbs: 28.3 }, units: [{ name: 'pancake', grams: 77 }] },
  { id: 'pasta-cooked', name: 'Pasta (cooked)', category: 'carb', emoji: '🍝', aliases: ['spaghetti', 'noodles', 'penne'], per100: { cal: 158, protein: 5.8, carbs: 30.9 }, units: [{ name: 'cup', grams: 140 }] },
  { id: 'pasta-dry', name: 'Pasta (dry)', category: 'carb', emoji: '🍝', aliases: ['dry pasta'], per100: { cal: 371, protein: 13.0, carbs: 74.7 }, units: [{ name: 'serving', grams: 56 }] },
  { id: 'pita-bread', name: 'Pita bread', category: 'carb', emoji: '🫓', aliases: ['pita'], per100: { cal: 275, protein: 9.1, carbs: 55.7 }, units: [{ name: 'pita', grams: 60 }] },
  { id: 'potato-baked', name: 'Potato (baked)', category: 'carb', emoji: '🥔', aliases: ['baked potato'], per100: { cal: 93, protein: 2.5, carbs: 21.2 }, units: [{ name: 'medium potato', grams: 173 }] },
  { id: 'potato-raw', name: 'Potato (raw)', category: 'carb', emoji: '🥔', per100: { cal: 77, protein: 2.0, carbs: 17.5 }, units: [{ name: 'medium potato', grams: 213 }] },
  { id: 'quinoa-cooked', name: 'Quinoa (cooked)', category: 'carb', emoji: '🍚', aliases: ['quinoa'], per100: { cal: 120, protein: 4.4, carbs: 21.3 }, units: [{ name: 'cup', grams: 185 }] },
  { id: 'rice-cake', name: 'Rice cake', category: 'carb', emoji: '🍘', aliases: ['rice cakes'], per100: { cal: 387, protein: 8.2, carbs: 81.5 }, units: [{ name: 'cake', grams: 9 }] },
  { id: 'sweet-potato-baked', name: 'Sweet potato (baked)', category: 'carb', emoji: '🍠', per100: { cal: 90, protein: 2.0, carbs: 20.7 }, units: [{ name: 'medium sweet potato', grams: 114 }] },
  { id: 'sweet-potato-raw', name: 'Sweet potato (raw)', category: 'carb', emoji: '🍠', per100: { cal: 86, protein: 1.6, carbs: 20.1 }, units: [{ name: 'medium sweet potato', grams: 130 }] },
  { id: 'tortilla-corn', name: 'Tortilla (corn)', category: 'carb', emoji: '🌮', aliases: ['corn tortilla'], per100: { cal: 218, protein: 5.7, carbs: 44.6 }, units: [{ name: 'tortilla', grams: 26 }] },
  { id: 'tortilla-flour', name: 'Tortilla (flour)', category: 'carb', emoji: '🌯', aliases: ['flour tortilla', 'wrap'], per100: { cal: 306, protein: 8.3, carbs: 49.6 }, units: [{ name: 'tortilla', grams: 45 }, { name: 'burrito tortilla', grams: 70 }] },
  { id: 'waffle', name: 'Waffle', category: 'carb', emoji: '🧇', aliases: ['eggo'], per100: { cal: 291, protein: 7.9, carbs: 32.9 }, units: [{ name: 'waffle', grams: 75 }] },
  { id: 'white-rice-cooked', name: 'White rice (cooked)', category: 'carb', emoji: '🍚', aliases: ['rice', 'jasmine rice'], per100: { cal: 130, protein: 2.7, carbs: 28.2 }, units: [{ name: 'cup', grams: 158 }] },
  { id: 'white-rice-dry', name: 'White rice (dry)', category: 'carb', emoji: '🍚', per100: { cal: 365, protein: 7.1, carbs: 80.0 }, units: [{ name: 'cup', grams: 185 }] },

  // ── veg ──
  { id: 'arugula', name: 'Arugula', category: 'veg', emoji: '🥬', aliases: ['rocket'], per100: { cal: 25, protein: 2.6, carbs: 3.7 }, units: [{ name: 'cup', grams: 20 }] },
  { id: 'asparagus', name: 'Asparagus', category: 'veg', emoji: '🌿', per100: { cal: 20, protein: 2.2, carbs: 3.9 }, units: [{ name: 'spear', grams: 16 }, { name: 'cup', grams: 134 }] },
  { id: 'avocado', name: 'Avocado', category: 'veg', emoji: '🥑', aliases: ['avo'], per100: { cal: 160, protein: 2.0, carbs: 8.5 }, units: [{ name: 'half avocado', grams: 75 }, { name: 'avocado', grams: 150 }] },
  { id: 'beets', name: 'Beets', category: 'veg', emoji: '🍠', aliases: ['beetroot'], per100: { cal: 43, protein: 1.6, carbs: 9.6 }, units: [{ name: 'beet', grams: 82 }, { name: 'cup', grams: 136 }] },
  { id: 'bell-pepper', name: 'Bell pepper', category: 'veg', emoji: '🫑', aliases: ['capsicum', 'red pepper'], per100: { cal: 26, protein: 1.0, carbs: 6.0 }, units: [{ name: 'pepper', grams: 119 }] },
  { id: 'bok-choy', name: 'Bok choy', category: 'veg', emoji: '🥬', aliases: ['pak choi'], per100: { cal: 13, protein: 1.5, carbs: 2.2 }, units: [{ name: 'cup', grams: 70 }] },
  { id: 'broccoli', name: 'Broccoli', category: 'veg', emoji: '🥦', per100: { cal: 34, protein: 2.8, carbs: 6.6 }, units: [{ name: 'cup', grams: 91 }] },
  { id: 'brussels-sprouts', name: 'Brussels sprouts', category: 'veg', emoji: '🥬', per100: { cal: 43, protein: 3.4, carbs: 9.0 }, units: [{ name: 'cup', grams: 88 }, { name: 'sprout', grams: 19 }] },
  { id: 'butternut-squash', name: 'Butternut squash', category: 'veg', emoji: '🎃', per100: { cal: 45, protein: 1.0, carbs: 11.7 }, units: [{ name: 'cup', grams: 140 }] },
  { id: 'cabbage', name: 'Cabbage', category: 'veg', emoji: '🥬', per100: { cal: 25, protein: 1.3, carbs: 5.8 }, units: [{ name: 'cup', grams: 89 }] },
  { id: 'carrot', name: 'Carrot', category: 'veg', emoji: '🥕', aliases: ['carrots'], per100: { cal: 41, protein: 0.9, carbs: 9.6 }, units: [{ name: 'carrot', grams: 61 }, { name: 'baby carrot', grams: 10 }, { name: 'cup', grams: 128 }] },
  { id: 'cauliflower', name: 'Cauliflower', category: 'veg', emoji: '🥦', per100: { cal: 25, protein: 1.9, carbs: 5.0 }, units: [{ name: 'cup', grams: 107 }] },
  { id: 'celery', name: 'Celery', category: 'veg', emoji: '🥬', per100: { cal: 14, protein: 0.7, carbs: 3.0 }, units: [{ name: 'stalk', grams: 40 }, { name: 'cup', grams: 101 }] },
  { id: 'sweet-corn', name: 'Corn (sweet)', category: 'veg', emoji: '🌽', aliases: ['corn', 'corn on the cob'], per100: { cal: 86, protein: 3.3, carbs: 18.7 }, units: [{ name: 'ear', grams: 103 }, { name: 'cup', grams: 145 }] },
  { id: 'cucumber', name: 'Cucumber', category: 'veg', emoji: '🥒', per100: { cal: 15, protein: 0.7, carbs: 3.6 }, units: [{ name: 'cucumber', grams: 300 }, { name: 'cup', grams: 104 }] },
  { id: 'edamame', name: 'Edamame', category: 'veg', emoji: '🫛', aliases: ['soybeans'], per100: { cal: 121, protein: 11.9, carbs: 8.9 }, units: [{ name: 'cup', grams: 155 }] },
  { id: 'eggplant', name: 'Eggplant', category: 'veg', emoji: '🍆', aliases: ['aubergine'], per100: { cal: 25, protein: 1.0, carbs: 5.9 }, units: [{ name: 'cup', grams: 82 }] },
  { id: 'garlic', name: 'Garlic', category: 'veg', emoji: '🧄', per100: { cal: 149, protein: 6.4, carbs: 33.1 }, units: [{ name: 'clove', grams: 3 }] },
  { id: 'green-beans', name: 'Green beans', category: 'veg', emoji: '🫛', aliases: ['string beans'], per100: { cal: 31, protein: 1.8, carbs: 7.0 }, units: [{ name: 'cup', grams: 100 }] },
  { id: 'jalapeno', name: 'Jalapeno', category: 'veg', emoji: '🌶️', per100: { cal: 29, protein: 0.9, carbs: 6.5 }, units: [{ name: 'pepper', grams: 14 }] },
  { id: 'kale', name: 'Kale', category: 'veg', emoji: '🥬', per100: { cal: 35, protein: 2.9, carbs: 4.4 }, units: [{ name: 'cup', grams: 21 }] },
  { id: 'kimchi', name: 'Kimchi', category: 'veg', emoji: '🥬', per100: { cal: 15, protein: 1.1, carbs: 2.4 }, units: [{ name: 'cup', grams: 150 }] },
  { id: 'lettuce-iceberg', name: 'Lettuce (iceberg)', category: 'veg', emoji: '🥬', aliases: ['iceberg'], per100: { cal: 14, protein: 0.9, carbs: 3.0 }, units: [{ name: 'cup', grams: 72 }] },
  { id: 'lettuce-romaine', name: 'Lettuce (romaine)', category: 'veg', emoji: '🥬', aliases: ['romaine', 'cos lettuce', 'lettuce'], per100: { cal: 17, protein: 1.2, carbs: 3.3 }, units: [{ name: 'cup', grams: 47 }] },
  { id: 'mushrooms', name: 'Mushrooms', category: 'veg', emoji: '🍄', aliases: ['button mushrooms', 'cremini'], per100: { cal: 22, protein: 3.1, carbs: 3.3 }, units: [{ name: 'cup', grams: 70 }, { name: 'mushroom', grams: 18 }] },
  { id: 'onion', name: 'Onion', category: 'veg', emoji: '🧅', per100: { cal: 40, protein: 1.1, carbs: 9.3 }, units: [{ name: 'onion', grams: 110 }, { name: 'cup', grams: 160 }] },
  { id: 'peas', name: 'Peas', category: 'veg', emoji: '🫛', aliases: ['green peas'], per100: { cal: 81, protein: 5.4, carbs: 14.5 }, units: [{ name: 'cup', grams: 145 }] },
  { id: 'pickles', name: 'Pickles', category: 'veg', emoji: '🥒', aliases: ['dill pickle'], per100: { cal: 11, protein: 0.6, carbs: 2.3 }, units: [{ name: 'pickle', grams: 65 }, { name: 'spear', grams: 35 }] },
  { id: 'salsa', name: 'Salsa', category: 'veg', emoji: '🍅', aliases: ['pico de gallo'], per100: { cal: 29, protein: 1.5, carbs: 6.5 }, units: [{ name: 'tbsp', grams: 16 }, { name: 'cup', grams: 259 }] },
  { id: 'sauerkraut', name: 'Sauerkraut', category: 'veg', emoji: '🥬', per100: { cal: 19, protein: 0.9, carbs: 4.3 }, units: [{ name: 'cup', grams: 142 }] },
  { id: 'scallion', name: 'Scallion', category: 'veg', emoji: '🧅', aliases: ['green onion', 'spring onion'], per100: { cal: 32, protein: 1.8, carbs: 7.3 }, units: [{ name: 'scallion', grams: 15 }] },
  { id: 'spinach', name: 'Spinach', category: 'veg', emoji: '🥬', per100: { cal: 23, protein: 2.9, carbs: 3.6 }, units: [{ name: 'cup', grams: 30 }] },
  { id: 'tomato', name: 'Tomato', category: 'veg', emoji: '🍅', aliases: ['tomatoes'], per100: { cal: 18, protein: 0.9, carbs: 3.9 }, units: [{ name: 'tomato', grams: 123 }, { name: 'cherry tomato', grams: 17 }] },
  { id: 'zucchini', name: 'Zucchini', category: 'veg', emoji: '🥒', aliases: ['courgette'], per100: { cal: 17, protein: 1.2, carbs: 3.1 }, units: [{ name: 'zucchini', grams: 196 }, { name: 'cup', grams: 124 }] },

  // ── fruit ──
  { id: 'apple', name: 'Apple', category: 'fruit', emoji: '🍎', per100: { cal: 52, protein: 0.3, carbs: 13.8 }, units: [{ name: 'medium apple', grams: 182 }, { name: 'small apple', grams: 149 }] },
  { id: 'applesauce-unsweetened', name: 'Applesauce (unsweetened)', category: 'fruit', emoji: '🍎', aliases: ['applesauce'], per100: { cal: 42, protein: 0.2, carbs: 11.3 }, units: [{ name: 'pouch', grams: 90 }, { name: 'cup', grams: 244 }] },
  { id: 'banana', name: 'Banana', category: 'fruit', emoji: '🍌', per100: { cal: 89, protein: 1.1, carbs: 22.8 }, units: [{ name: 'medium banana', grams: 118 }, { name: 'large banana', grams: 136 }] },
  { id: 'blackberries', name: 'Blackberries', category: 'fruit', emoji: '🫐', per100: { cal: 43, protein: 1.4, carbs: 9.6 }, units: [{ name: 'cup', grams: 144 }] },
  { id: 'blueberries', name: 'Blueberries', category: 'fruit', emoji: '🫐', per100: { cal: 57, protein: 0.7, carbs: 14.5 }, units: [{ name: 'cup', grams: 148 }] },
  { id: 'cantaloupe', name: 'Cantaloupe', category: 'fruit', emoji: '🍈', per100: { cal: 34, protein: 0.8, carbs: 8.2 }, units: [{ name: 'cup', grams: 160 }] },
  { id: 'cherries', name: 'Cherries', category: 'fruit', emoji: '🍒', per100: { cal: 63, protein: 1.1, carbs: 16.0 }, units: [{ name: 'cup', grams: 138 }, { name: 'cherry', grams: 8 }] },
  { id: 'clementine', name: 'Clementine', category: 'fruit', emoji: '🍊', aliases: ['mandarin', 'cutie'], per100: { cal: 47, protein: 0.9, carbs: 12.0 }, units: [{ name: 'clementine', grams: 74 }] },
  { id: 'dates-medjool', name: 'Dates (Medjool)', category: 'fruit', emoji: '🌴', aliases: ['dates'], per100: { cal: 277, protein: 1.8, carbs: 75.0 }, units: [{ name: 'date', grams: 24 }] },
  { id: 'dried-cranberries', name: 'Dried cranberries', category: 'fruit', emoji: '🍒', aliases: ['craisins'], per100: { cal: 308, protein: 0.1, carbs: 82.4 }, units: [{ name: 'tbsp', grams: 8 }, { name: 'cup', grams: 120 }] },
  { id: 'dried-mango', name: 'Dried mango', category: 'fruit', emoji: '🥭', per100: { cal: 319, protein: 2.5, carbs: 78.6 }, units: [{ name: 'piece', grams: 20 }] },
  { id: 'grapefruit', name: 'Grapefruit', category: 'fruit', emoji: '🍊', per100: { cal: 42, protein: 0.8, carbs: 10.7 }, units: [{ name: 'half grapefruit', grams: 123 }] },
  { id: 'grapes', name: 'Grapes', category: 'fruit', emoji: '🍇', per100: { cal: 69, protein: 0.7, carbs: 18.1 }, units: [{ name: 'cup', grams: 151 }, { name: 'grape', grams: 5 }] },
  { id: 'honeydew', name: 'Honeydew', category: 'fruit', emoji: '🍈', per100: { cal: 36, protein: 0.5, carbs: 9.1 }, units: [{ name: 'cup', grams: 170 }] },
  { id: 'kiwi', name: 'Kiwi', category: 'fruit', emoji: '🥝', per100: { cal: 61, protein: 1.1, carbs: 14.7 }, units: [{ name: 'kiwi', grams: 69 }] },
  { id: 'lemon', name: 'Lemon', category: 'fruit', emoji: '🍋', per100: { cal: 29, protein: 1.1, carbs: 9.3 }, units: [{ name: 'lemon', grams: 58 }, { name: 'wedge', grams: 7 }] },
  { id: 'lime', name: 'Lime', category: 'fruit', emoji: '🍋', per100: { cal: 30, protein: 0.7, carbs: 10.5 }, units: [{ name: 'lime', grams: 67 }, { name: 'wedge', grams: 8 }] },
  { id: 'mango', name: 'Mango', category: 'fruit', emoji: '🥭', per100: { cal: 60, protein: 0.8, carbs: 15.0 }, units: [{ name: 'cup', grams: 165 }, { name: 'mango', grams: 207 }] },
  { id: 'nectarine', name: 'Nectarine', category: 'fruit', emoji: '🍑', per100: { cal: 44, protein: 1.1, carbs: 10.6 }, units: [{ name: 'nectarine', grams: 142 }] },
  { id: 'orange', name: 'Orange', category: 'fruit', emoji: '🍊', per100: { cal: 47, protein: 0.9, carbs: 11.8 }, units: [{ name: 'medium orange', grams: 131 }] },
  { id: 'papaya', name: 'Papaya', category: 'fruit', emoji: '🥭', per100: { cal: 43, protein: 0.5, carbs: 10.8 }, units: [{ name: 'cup', grams: 145 }] },
  { id: 'peach', name: 'Peach', category: 'fruit', emoji: '🍑', per100: { cal: 39, protein: 0.9, carbs: 9.5 }, units: [{ name: 'medium peach', grams: 150 }] },
  { id: 'pear', name: 'Pear', category: 'fruit', emoji: '🍐', per100: { cal: 57, protein: 0.4, carbs: 15.2 }, units: [{ name: 'medium pear', grams: 178 }] },
  { id: 'pineapple', name: 'Pineapple', category: 'fruit', emoji: '🍍', per100: { cal: 50, protein: 0.5, carbs: 13.1 }, units: [{ name: 'cup', grams: 165 }] },
  { id: 'plum', name: 'Plum', category: 'fruit', emoji: '🍑', per100: { cal: 46, protein: 0.7, carbs: 11.4 }, units: [{ name: 'plum', grams: 66 }] },
  { id: 'pomegranate', name: 'Pomegranate (arils)', category: 'fruit', emoji: '🍎', aliases: ['pomegranate seeds'], per100: { cal: 83, protein: 1.7, carbs: 18.7 }, units: [{ name: 'cup', grams: 174 }, { name: 'pomegranate', grams: 282 }] },
  { id: 'raisins', name: 'Raisins', category: 'fruit', emoji: '🍇', per100: { cal: 299, protein: 3.1, carbs: 79.2 }, units: [{ name: 'small box', grams: 43 }, { name: 'tbsp', grams: 9 }] },
  { id: 'raspberries', name: 'Raspberries', category: 'fruit', emoji: '🍓', per100: { cal: 52, protein: 1.2, carbs: 11.9 }, units: [{ name: 'cup', grams: 123 }] },
  { id: 'strawberries', name: 'Strawberries', category: 'fruit', emoji: '🍓', per100: { cal: 32, protein: 0.7, carbs: 7.7 }, units: [{ name: 'cup', grams: 152 }, { name: 'strawberry', grams: 12 }] },
  { id: 'watermelon', name: 'Watermelon', category: 'fruit', emoji: '🍉', per100: { cal: 30, protein: 0.6, carbs: 7.5 }, units: [{ name: 'cup', grams: 152 }, { name: 'wedge', grams: 286 }] },

  // ── dairy ──
  { id: 'american-cheese', name: 'American cheese', category: 'dairy', emoji: '🧀', aliases: ['kraft singles'], per100: { cal: 330, protein: 17.0, carbs: 7.0 }, units: [{ name: 'slice', grams: 21 }] },
  { id: 'butter', name: 'Butter', category: 'dairy', emoji: '🧈', per100: { cal: 717, protein: 0.9, carbs: 0.1 }, units: [{ name: 'tbsp', grams: 14 }, { name: 'pat', grams: 5 }] },
  { id: 'cheddar-cheese', name: 'Cheddar cheese', category: 'dairy', emoji: '🧀', aliases: ['cheddar'], per100: { cal: 403, protein: 24.9, carbs: 1.3 }, units: [{ name: 'slice', grams: 21 }, { name: 'oz', grams: 28 }] },
  { id: 'cottage-cheese-full', name: 'Cottage cheese (full-fat)', category: 'dairy', emoji: '🧀', aliases: ['4% cottage cheese'], per100: { cal: 98, protein: 11.1, carbs: 3.4 }, units: [{ name: 'half cup', grams: 105 }, { name: 'cup', grams: 210 }] },
  { id: 'cottage-cheese-lowfat', name: 'Cottage cheese (low-fat)', category: 'dairy', emoji: '🧀', aliases: ['2% cottage cheese', 'cottage cheese'], per100: { cal: 84, protein: 11.0, carbs: 4.3 }, units: [{ name: 'half cup', grams: 113 }, { name: 'cup', grams: 226 }] },
  { id: 'cream-cheese', name: 'Cream cheese', category: 'dairy', emoji: '🧀', per100: { cal: 342, protein: 5.9, carbs: 5.5 }, units: [{ name: 'tbsp', grams: 15 }, { name: 'oz', grams: 28 }] },
  { id: 'feta-cheese', name: 'Feta cheese', category: 'dairy', emoji: '🧀', aliases: ['feta'], per100: { cal: 264, protein: 14.2, carbs: 4.1 }, units: [{ name: 'oz', grams: 28 }, { name: 'tbsp crumbled', grams: 9 }] },
  { id: 'goat-cheese', name: 'Goat cheese', category: 'dairy', emoji: '🧀', aliases: ['chevre'], per100: { cal: 264, protein: 18.5, carbs: 2.5 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'greek-yogurt-nonfat', name: 'Greek yogurt (0%)', category: 'dairy', emoji: '🥣', aliases: ['greek yogurt', 'nonfat greek yogurt'], per100: { cal: 59, protein: 10.3, carbs: 3.6 }, units: [{ name: 'container', grams: 170 }, { name: 'cup', grams: 245 }] },
  { id: 'greek-yogurt-full', name: 'Greek yogurt (full-fat)', category: 'dairy', emoji: '🥣', aliases: ['5% greek yogurt'], per100: { cal: 97, protein: 9.0, carbs: 3.9 }, units: [{ name: 'container', grams: 170 }, { name: 'cup', grams: 245 }] },
  { id: 'half-and-half', name: 'Half and half', category: 'dairy', emoji: '🥛', per100: { cal: 131, protein: 3.1, carbs: 4.3 }, units: [{ name: 'tbsp', grams: 15 }], liquid: true },
  { id: 'heavy-cream', name: 'Heavy cream', category: 'dairy', emoji: '🥛', aliases: ['heavy whipping cream'], per100: { cal: 340, protein: 2.8, carbs: 2.7 }, units: [{ name: 'tbsp', grams: 15 }], liquid: true },
  { id: 'ice-cream-vanilla', name: 'Ice cream (vanilla)', category: 'dairy', emoji: '🍦', aliases: ['ice cream'], per100: { cal: 207, protein: 3.5, carbs: 23.6 }, units: [{ name: 'scoop', grams: 66 }, { name: 'cup', grams: 132 }] },
  { id: 'kefir', name: 'Kefir', category: 'dairy', emoji: '🥛', per100: { cal: 46, protein: 4.6, carbs: 5.0 }, units: [{ name: 'cup', grams: 240 }], liquid: true, hydrating: true },
  { id: 'milk-2', name: 'Milk (2%)', category: 'dairy', emoji: '🥛', aliases: ['2% milk', 'reduced fat milk'], per100: { cal: 50, protein: 3.3, carbs: 4.8 }, units: [{ name: 'cup', grams: 240 }, { name: 'splash', grams: 30 }], liquid: true, hydrating: true },
  { id: 'milk-skim', name: 'Milk (skim)', category: 'dairy', emoji: '🥛', aliases: ['skim milk', 'fat free milk', 'nonfat milk'], per100: { cal: 34, protein: 3.4, carbs: 5.0 }, units: [{ name: 'cup', grams: 240 }, { name: 'splash', grams: 30 }], liquid: true, hydrating: true },
  { id: 'milk-whole', name: 'Milk (whole)', category: 'dairy', emoji: '🥛', aliases: ['whole milk', 'milk'], per100: { cal: 61, protein: 3.2, carbs: 4.8 }, units: [{ name: 'cup', grams: 240 }, { name: 'splash', grams: 30 }], liquid: true, hydrating: true },
  { id: 'mozzarella-cheese', name: 'Mozzarella cheese', category: 'dairy', emoji: '🧀', aliases: ['mozzarella'], per100: { cal: 300, protein: 22.2, carbs: 2.2 }, units: [{ name: 'oz', grams: 28 }, { name: 'cup shredded', grams: 112 }] },
  { id: 'parmesan-cheese', name: 'Parmesan cheese', category: 'dairy', emoji: '🧀', aliases: ['parm', 'parmigiano'], per100: { cal: 431, protein: 38.5, carbs: 4.1 }, units: [{ name: 'tbsp grated', grams: 5 }, { name: 'oz', grams: 28 }] },
  { id: 'ricotta-cheese', name: 'Ricotta cheese', category: 'dairy', emoji: '🧀', aliases: ['ricotta'], per100: { cal: 174, protein: 11.3, carbs: 3.0 }, units: [{ name: 'half cup', grams: 124 }, { name: 'cup', grams: 246 }] },
  { id: 'sour-cream', name: 'Sour cream', category: 'dairy', emoji: '🥣', per100: { cal: 198, protein: 2.4, carbs: 4.6 }, units: [{ name: 'tbsp', grams: 12 }] },
  { id: 'string-cheese', name: 'String cheese', category: 'dairy', emoji: '🧀', aliases: ['cheese stick'], per100: { cal: 286, protein: 25.0, carbs: 3.6 }, units: [{ name: 'stick', grams: 28 }] },
  { id: 'swiss-cheese', name: 'Swiss cheese', category: 'dairy', emoji: '🧀', aliases: ['swiss'], per100: { cal: 380, protein: 26.9, carbs: 5.4 }, units: [{ name: 'slice', grams: 21 }, { name: 'oz', grams: 28 }] },
  { id: 'yogurt-flavored', name: 'Yogurt (fruit-flavored)', category: 'dairy', emoji: '🥣', aliases: ['fruit yogurt'], per100: { cal: 102, protein: 4.4, carbs: 19.1 }, units: [{ name: 'container', grams: 170 }] },
  { id: 'yogurt-plain', name: 'Yogurt (plain, whole milk)', category: 'dairy', emoji: '🥣', aliases: ['plain yogurt'], per100: { cal: 61, protein: 3.5, carbs: 4.7 }, units: [{ name: 'cup', grams: 245 }, { name: 'container', grams: 170 }] },

  // ── fat ──
  { id: 'almond-butter', name: 'Almond butter', category: 'fat', emoji: '🥜', per100: { cal: 614, protein: 21.0, carbs: 18.8 }, units: [{ name: 'tbsp', grams: 16 }] },
  { id: 'almonds', name: 'Almonds', category: 'fat', emoji: '🌰', per100: { cal: 579, protein: 21.2, carbs: 21.6 }, units: [{ name: 'oz', grams: 28 }, { name: 'almond', grams: 1.2 }] },
  { id: 'avocado-oil', name: 'Avocado oil', category: 'fat', emoji: '🥑', per100: { cal: 884, protein: 0, carbs: 0 }, units: [{ name: 'tbsp', grams: 14 }, { name: 'tsp', grams: 5 }] },
  { id: 'canola-oil', name: 'Canola oil', category: 'fat', emoji: '🫒', aliases: ['vegetable oil'], per100: { cal: 884, protein: 0, carbs: 0 }, units: [{ name: 'tbsp', grams: 14 }, { name: 'tsp', grams: 5 }] },
  { id: 'cashews', name: 'Cashews', category: 'fat', emoji: '🥜', per100: { cal: 553, protein: 18.2, carbs: 30.2 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'chia-seeds', name: 'Chia seeds', category: 'fat', emoji: '🌱', aliases: ['chia'], per100: { cal: 486, protein: 16.5, carbs: 42.1 }, units: [{ name: 'tbsp', grams: 12 }] },
  { id: 'coconut-oil', name: 'Coconut oil', category: 'fat', emoji: '🥥', per100: { cal: 862, protein: 0, carbs: 0 }, units: [{ name: 'tbsp', grams: 14 }, { name: 'tsp', grams: 5 }] },
  { id: 'flaxseed-ground', name: 'Flaxseed (ground)', category: 'fat', emoji: '🌱', aliases: ['flax', 'ground flax'], per100: { cal: 534, protein: 18.3, carbs: 28.9 }, units: [{ name: 'tbsp', grams: 7 }] },
  { id: 'mayonnaise', name: 'Mayonnaise', category: 'fat', emoji: '🫙', aliases: ['mayo'], per100: { cal: 680, protein: 1.0, carbs: 0.6 }, units: [{ name: 'tbsp', grams: 14 }] },
  { id: 'olive-oil', name: 'Olive oil', category: 'fat', emoji: '🫒', aliases: ['evoo', 'extra virgin olive oil'], per100: { cal: 884, protein: 0, carbs: 0 }, units: [{ name: 'tbsp', grams: 14 }, { name: 'tsp', grams: 5 }] },
  { id: 'peanut-butter', name: 'Peanut butter', category: 'fat', emoji: '🥜', aliases: ['pb'], per100: { cal: 588, protein: 25.1, carbs: 19.6 }, units: [{ name: 'tbsp', grams: 16 }] },
  { id: 'peanuts', name: 'Peanuts', category: 'fat', emoji: '🥜', per100: { cal: 567, protein: 25.8, carbs: 16.1 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'pecans', name: 'Pecans', category: 'fat', emoji: '🌰', per100: { cal: 691, protein: 9.2, carbs: 13.9 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'pistachios', name: 'Pistachios', category: 'fat', emoji: '🥜', per100: { cal: 560, protein: 20.2, carbs: 27.2 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'sunflower-seeds', name: 'Sunflower seeds', category: 'fat', emoji: '🌻', per100: { cal: 584, protein: 20.8, carbs: 20.0 }, units: [{ name: 'oz', grams: 28 }] },
  { id: 'walnuts', name: 'Walnuts', category: 'fat', emoji: '🌰', per100: { cal: 654, protein: 15.2, carbs: 13.7 }, units: [{ name: 'oz', grams: 28 }] },

  // ── drink ──
  { id: 'almond-milk', name: 'Almond milk (unsweetened)', category: 'drink', emoji: '🥛', aliases: ['almond milk'], per100: { cal: 13, protein: 0.4, carbs: 0.4 }, units: [{ name: 'cup', grams: 240 }, { name: 'splash', grams: 30 }], liquid: true, hydrating: true },
  { id: 'apple-juice', name: 'Apple juice', category: 'drink', emoji: '🧃', per100: { cal: 46, protein: 0.1, carbs: 11.3 }, units: [{ name: 'cup', grams: 240 }, { name: 'juice box', grams: 200 }], liquid: true, hydrating: true },
  { id: 'beer', name: 'Beer', category: 'drink', emoji: '🍺', aliases: ['lager', 'ipa'], per100: { cal: 43, protein: 0.5, carbs: 3.6 }, units: [{ name: 'can', grams: 355 }, { name: 'pint', grams: 473 }], liquid: true },
  { id: 'black-tea', name: 'Black tea', category: 'drink', emoji: '🍵', aliases: ['tea'], per100: { cal: 1, protein: 0, carbs: 0.3 }, units: [{ name: 'cup', grams: 240 }], liquid: true, hydrating: true, caffeinePer100: 20 },
  { id: 'chocolate-milk', name: 'Chocolate milk', category: 'drink', emoji: '🥛', per100: { cal: 83, protein: 3.4, carbs: 10.4 }, units: [{ name: 'cup', grams: 240 }], liquid: true, hydrating: true },
  { id: 'coca-cola', name: 'Coca-Cola', category: 'drink', emoji: '🥤', aliases: ['coke', 'cola', 'coca cola'], per100: { cal: 39, protein: 0, carbs: 10.6 }, units: [{ name: 'can', grams: 355 }, { name: 'bottle', grams: 500 }], liquid: true, hydrating: true, caffeinePer100: 9.6 },
  { id: 'coconut-water', name: 'Coconut water', category: 'drink', emoji: '🥥', per100: { cal: 19, protein: 0.7, carbs: 3.7 }, units: [{ name: 'cup', grams: 240 }, { name: 'bottle', grams: 330 }], liquid: true, hydrating: true },
  { id: 'coffee-black', name: 'Coffee (black)', category: 'drink', emoji: '☕', aliases: ['coffee', 'drip coffee', 'americano'], per100: { cal: 1, protein: 0.1, carbs: 0 }, units: [{ name: 'cup', grams: 240 }, { name: 'mug', grams: 355 }], liquid: true, hydrating: true, caffeinePer100: 40 },
  { id: 'cold-brew', name: 'Cold brew coffee', category: 'drink', emoji: '☕', aliases: ['cold brew'], per100: { cal: 2, protein: 0.1, carbs: 0 }, units: [{ name: 'cup', grams: 240 }, { name: 'large cup', grams: 473 }], liquid: true, hydrating: true, caffeinePer100: 43 },
  { id: 'diet-coke', name: 'Diet Coke', category: 'drink', emoji: '🥤', aliases: ['diet cola', 'coke zero', 'diet soda'], per100: { cal: 0, protein: 0, carbs: 0 }, units: [{ name: 'can', grams: 355 }, { name: 'bottle', grams: 500 }], liquid: true, hydrating: true, caffeinePer100: 12.7 },
  { id: 'espresso', name: 'Espresso', category: 'drink', emoji: '☕', per100: { cal: 9, protein: 0.1, carbs: 1.7 }, units: [{ name: 'shot', grams: 30 }, { name: 'double shot', grams: 60 }], liquid: true, hydrating: true, caffeinePer100: 212 },
  { id: 'gatorade', name: 'Gatorade', category: 'drink', emoji: '🥤', aliases: ['sports drink', 'powerade'], per100: { cal: 24, protein: 0, carbs: 6.1 }, units: [{ name: 'bottle', grams: 591 }, { name: 'cup', grams: 240 }], liquid: true, hydrating: true },
  { id: 'green-tea', name: 'Green tea', category: 'drink', emoji: '🍵', aliases: ['matcha'], per100: { cal: 0, protein: 0, carbs: 0 }, units: [{ name: 'cup', grams: 240 }], liquid: true, hydrating: true, caffeinePer100: 12 },
  { id: 'kombucha', name: 'Kombucha', category: 'drink', emoji: '🍹', per100: { cal: 13, protein: 0.1, carbs: 3.0 }, units: [{ name: 'bottle', grams: 480 }, { name: 'cup', grams: 240 }], liquid: true, hydrating: true },
  { id: 'latte-whole-milk', name: 'Latte (whole milk)', category: 'drink', emoji: '☕', aliases: ['latte'], per100: { cal: 45, protein: 2.4, carbs: 3.6 }, units: [{ name: 'small', grams: 355 }, { name: 'large', grams: 473 }], liquid: true, hydrating: true, caffeinePer100: 21 },
  { id: 'lemonade', name: 'Lemonade', category: 'drink', emoji: '🍋', per100: { cal: 40, protein: 0.1, carbs: 10.4 }, units: [{ name: 'cup', grams: 240 }, { name: 'bottle', grams: 500 }], liquid: true, hydrating: true },
  { id: 'light-beer', name: 'Light beer', category: 'drink', emoji: '🍺', aliases: ['michelob ultra', 'bud light'], per100: { cal: 29, protein: 0.2, carbs: 1.6 }, units: [{ name: 'can', grams: 355 }], liquid: true },
  { id: 'monster-energy', name: 'Monster Energy', category: 'drink', emoji: '⚡', aliases: ['monster', 'energy drink'], per100: { cal: 44, protein: 0, carbs: 11.5 }, units: [{ name: 'can', grams: 473 }], liquid: true, hydrating: true, caffeinePer100: 36 },
  { id: 'oat-milk', name: 'Oat milk', category: 'drink', emoji: '🥛', aliases: ['oatly'], per100: { cal: 48, protein: 0.8, carbs: 6.5 }, units: [{ name: 'cup', grams: 240 }, { name: 'splash', grams: 30 }], liquid: true, hydrating: true },
  { id: 'orange-juice', name: 'Orange juice', category: 'drink', emoji: '🍊', aliases: ['oj'], per100: { cal: 45, protein: 0.7, carbs: 10.4 }, units: [{ name: 'cup', grams: 240 }, { name: 'bottle', grams: 355 }], liquid: true, hydrating: true },
  { id: 'protein-shake-premade', name: 'Protein shake (premade)', category: 'drink', emoji: '🥤', aliases: ['premier protein', 'fairlife shake'], per100: { cal: 49, protein: 9.2, carbs: 1.2 }, units: [{ name: 'bottle', grams: 325 }], liquid: true, hydrating: true },
  { id: 'red-bull', name: 'Red Bull', category: 'drink', emoji: '⚡', aliases: ['redbull'], per100: { cal: 45, protein: 0.4, carbs: 11.0 }, units: [{ name: 'can', grams: 250 }], liquid: true, hydrating: true, caffeinePer100: 32 },
  { id: 'smoothie-fruit', name: 'Smoothie (fruit)', category: 'drink', emoji: '🥤', aliases: ['smoothie'], per100: { cal: 58, protein: 1.2, carbs: 13.5 }, units: [{ name: 'cup', grams: 240 }, { name: 'bottle', grams: 450 }], liquid: true, hydrating: true },
  { id: 'soy-milk', name: 'Soy milk', category: 'drink', emoji: '🥛', per100: { cal: 43, protein: 3.0, carbs: 3.1 }, units: [{ name: 'cup', grams: 240 }, { name: 'splash', grams: 30 }], liquid: true, hydrating: true },
  { id: 'sparkling-water', name: 'Sparkling water', category: 'drink', emoji: '🫧', aliases: ['seltzer', 'la croix', 'soda water'], per100: { cal: 0, protein: 0, carbs: 0 }, units: [{ name: 'can', grams: 355 }, { name: 'bottle', grams: 500 }], liquid: true, hydrating: true },
  { id: 'sprite', name: 'Sprite', category: 'drink', emoji: '🥤', aliases: ['7up', 'lemon lime soda'], per100: { cal: 39, protein: 0, carbs: 10.6 }, units: [{ name: 'can', grams: 355 }, { name: 'bottle', grams: 500 }], liquid: true, hydrating: true },
  { id: 'vodka', name: 'Vodka', category: 'drink', emoji: '🍸', per100: { cal: 231, protein: 0, carbs: 0 }, units: [{ name: 'shot', grams: 44 }], liquid: true },
  { id: 'water', name: 'Water', category: 'drink', emoji: '💧', aliases: ['h2o'], per100: { cal: 0, protein: 0, carbs: 0 }, units: [{ name: 'cup', grams: 240 }, { name: 'bottle', grams: 500 }], liquid: true, hydrating: true },
  { id: 'whiskey', name: 'Whiskey', category: 'drink', emoji: '🥃', aliases: ['bourbon', 'scotch'], per100: { cal: 250, protein: 0, carbs: 0 }, units: [{ name: 'shot', grams: 44 }], liquid: true },
  { id: 'wine-red', name: 'Wine (red)', category: 'drink', emoji: '🍷', aliases: ['red wine'], per100: { cal: 85, protein: 0.1, carbs: 2.6 }, units: [{ name: 'glass', grams: 150 }], liquid: true },
  { id: 'wine-white', name: 'Wine (white)', category: 'drink', emoji: '🥂', aliases: ['white wine'], per100: { cal: 82, protein: 0.1, carbs: 2.6 }, units: [{ name: 'glass', grams: 150 }], liquid: true },

  // ── snack ──
  { id: 'brownie', name: 'Brownie', category: 'snack', emoji: '🍫', per100: { cal: 466, protein: 6.0, carbs: 57.0 }, units: [{ name: 'brownie', grams: 56 }] },
  { id: 'cheese-crackers', name: 'Cheese crackers', category: 'snack', emoji: '🍘', aliases: ['cheez its', 'goldfish'], per100: { cal: 500, protein: 10.0, carbs: 58.3 }, units: [{ name: 'serving', grams: 30 }] },
  { id: 'chocolate-chip-cookie', name: 'Chocolate chip cookie', category: 'snack', emoji: '🍪', aliases: ['cookie', 'cookies'], per100: { cal: 488, protein: 5.1, carbs: 64.6 }, units: [{ name: 'cookie', grams: 30 }] },
  { id: 'dark-chocolate', name: 'Dark chocolate', category: 'snack', emoji: '🍫', per100: { cal: 598, protein: 7.8, carbs: 45.9 }, units: [{ name: 'square', grams: 10 }, { name: 'oz', grams: 28 }] },
  { id: 'donut-glazed', name: 'Donut (glazed)', category: 'snack', emoji: '🍩', aliases: ['doughnut', 'krispy kreme'], per100: { cal: 403, protein: 6.4, carbs: 46.0 }, units: [{ name: 'donut', grams: 60 }] },
  { id: 'granola-bar', name: 'Granola bar', category: 'snack', emoji: '🥜', aliases: ['nature valley'], per100: { cal: 450, protein: 7.0, carbs: 64.0 }, units: [{ name: 'bar', grams: 40 }] },
  { id: 'guacamole', name: 'Guacamole', category: 'snack', emoji: '🥑', aliases: ['guac'], per100: { cal: 157, protein: 2.0, carbs: 8.5 }, units: [{ name: 'tbsp', grams: 15 }, { name: 'cup', grams: 230 }] },
  { id: 'gummy-bears', name: 'Gummy bears', category: 'snack', emoji: '🍬', aliases: ['gummies', 'haribo'], per100: { cal: 340, protein: 6.0, carbs: 77.5 }, units: [{ name: 'small bag', grams: 40 }, { name: 'bear', grams: 3 }] },
  { id: 'hummus', name: 'Hummus', category: 'snack', emoji: '🧆', per100: { cal: 166, protein: 7.9, carbs: 14.3 }, units: [{ name: 'tbsp', grams: 15 }, { name: 'cup', grams: 246 }] },
  { id: 'm-and-ms', name: 'M&Ms', category: 'snack', emoji: '🍫', aliases: ['m&ms', 'm and ms'], per100: { cal: 485, protein: 4.5, carbs: 70.0 }, units: [{ name: 'pack', grams: 49 }, { name: 'fun size pack', grams: 18 }] },
  { id: 'milk-chocolate', name: 'Milk chocolate', category: 'snack', emoji: '🍫', aliases: ['hershey bar', 'chocolate'], per100: { cal: 535, protein: 7.7, carbs: 59.4 }, units: [{ name: 'bar', grams: 45 }, { name: 'oz', grams: 28 }] },
  { id: 'muffin-blueberry', name: 'Muffin (blueberry)', category: 'snack', emoji: '🧁', aliases: ['muffin'], per100: { cal: 377, protein: 6.5, carbs: 54.0 }, units: [{ name: 'muffin', grams: 113 }] },
  { id: 'oreos', name: 'Oreo cookies', category: 'snack', emoji: '🍪', aliases: ['oreo', 'oreos'], per100: { cal: 471, protein: 5.0, carbs: 72.5 }, units: [{ name: 'cookie', grams: 11 }] },
  { id: 'popcorn-air-popped', name: 'Popcorn (air-popped)', category: 'snack', emoji: '🍿', aliases: ['popcorn'], per100: { cal: 387, protein: 12.9, carbs: 77.8 }, units: [{ name: 'cup', grams: 8 }] },
  { id: 'potato-chips', name: 'Potato chips', category: 'snack', emoji: '🥔', aliases: ['chips', 'lays', 'crisps'], per100: { cal: 536, protein: 6.6, carbs: 52.9 }, units: [{ name: 'oz', grams: 28 }, { name: 'chip', grams: 2 }] },
  { id: 'pretzels', name: 'Pretzels', category: 'snack', emoji: '🥨', per100: { cal: 384, protein: 10.0, carbs: 79.2 }, units: [{ name: 'oz', grams: 28 }, { name: 'mini pretzel', grams: 6 }] },
  { id: 'protein-bar', name: 'Protein bar', category: 'snack', emoji: '🍫', aliases: ['quest bar', 'rxbar'], per100: { cal: 320, protein: 33.0, carbs: 35.0 }, units: [{ name: 'bar', grams: 60 }] },
  { id: 'rice-krispies-treat', name: 'Rice Krispies treat', category: 'snack', emoji: '🍬', aliases: ['rice krispie treat'], per100: { cal: 409, protein: 2.5, carbs: 77.5 }, units: [{ name: 'bar', grams: 22 }] },
  { id: 'tortilla-chips', name: 'Tortilla chips', category: 'snack', emoji: '🌮', aliases: ['doritos', 'nachos'], per100: { cal: 497, protein: 7.2, carbs: 65.6 }, units: [{ name: 'oz', grams: 28 }, { name: 'chip', grams: 2.5 }] },
  { id: 'trail-mix', name: 'Trail mix', category: 'snack', emoji: '🥜', per100: { cal: 462, protein: 13.8, carbs: 44.9 }, units: [{ name: 'handful', grams: 40 }, { name: 'oz', grams: 28 }] },

  // ── condiment ──
  { id: 'alfredo-sauce', name: 'Alfredo sauce', category: 'condiment', emoji: '🥫', aliases: ['alfredo'], per100: { cal: 131, protein: 1.6, carbs: 3.3 }, units: [{ name: 'quarter cup', grams: 61 }, { name: 'tbsp', grams: 15 }] },
  { id: 'balsamic-vinegar', name: 'Balsamic vinegar', category: 'condiment', emoji: '🍶', aliases: ['balsamic'], per100: { cal: 88, protein: 0.5, carbs: 17.0 }, units: [{ name: 'tbsp', grams: 16 }] },
  { id: 'bbq-sauce', name: 'BBQ sauce', category: 'condiment', emoji: '🥫', aliases: ['barbecue sauce'], per100: { cal: 172, protein: 0.8, carbs: 40.8 }, units: [{ name: 'tbsp', grams: 17 }] },
  { id: 'buffalo-sauce', name: 'Buffalo sauce', category: 'condiment', emoji: '🌶️', aliases: ['franks redhot'], per100: { cal: 15, protein: 0.5, carbs: 2.0 }, units: [{ name: 'tbsp', grams: 15 }] },
  { id: 'caesar-dressing', name: 'Caesar dressing', category: 'condiment', emoji: '🥗', per100: { cal: 542, protein: 2.0, carbs: 3.5 }, units: [{ name: 'tbsp', grams: 15 }] },
  { id: 'honey', name: 'Honey', category: 'condiment', emoji: '🍯', per100: { cal: 304, protein: 0.3, carbs: 82.4 }, units: [{ name: 'tbsp', grams: 21 }, { name: 'tsp', grams: 7 }] },
  { id: 'hot-sauce', name: 'Hot sauce', category: 'condiment', emoji: '🌶️', aliases: ['tabasco', 'cholula'], per100: { cal: 11, protein: 0.5, carbs: 1.8 }, units: [{ name: 'tsp', grams: 5 }] },
  { id: 'jam', name: 'Jam', category: 'condiment', emoji: '🍓', aliases: ['jelly', 'preserves'], per100: { cal: 278, protein: 0.4, carbs: 68.9 }, units: [{ name: 'tbsp', grams: 20 }] },
  { id: 'ketchup', name: 'Ketchup', category: 'condiment', emoji: '🍅', aliases: ['catsup'], per100: { cal: 101, protein: 1.0, carbs: 27.4 }, units: [{ name: 'tbsp', grams: 17 }] },
  { id: 'maple-syrup', name: 'Maple syrup', category: 'condiment', emoji: '🍁', aliases: ['syrup'], per100: { cal: 260, protein: 0, carbs: 67.0 }, units: [{ name: 'tbsp', grams: 20 }] },
  { id: 'marinara-sauce', name: 'Marinara sauce', category: 'condiment', emoji: '🍅', aliases: ['pasta sauce', 'tomato sauce', 'red sauce'], per100: { cal: 50, protein: 1.4, carbs: 8.0 }, units: [{ name: 'half cup', grams: 125 }, { name: 'tbsp', grams: 16 }] },
  { id: 'mustard-yellow', name: 'Mustard (yellow)', category: 'condiment', emoji: '🌭', aliases: ['mustard', 'dijon'], per100: { cal: 60, protein: 3.7, carbs: 5.8 }, units: [{ name: 'tsp', grams: 5 }] },
  { id: 'pesto', name: 'Pesto', category: 'condiment', emoji: '🌿', per100: { cal: 425, protein: 4.8, carbs: 6.2 }, units: [{ name: 'tbsp', grams: 16 }] },
  { id: 'ranch-dressing', name: 'Ranch dressing', category: 'condiment', emoji: '🥗', aliases: ['ranch', 'hidden valley'], per100: { cal: 430, protein: 1.3, carbs: 6.0 }, units: [{ name: 'tbsp', grams: 15 }] },
  { id: 'soy-sauce', name: 'Soy sauce', category: 'condiment', emoji: '🍶', aliases: ['shoyu', 'tamari'], per100: { cal: 53, protein: 8.1, carbs: 4.9 }, units: [{ name: 'tbsp', grams: 16 }] },
  { id: 'sriracha', name: 'Sriracha', category: 'condiment', emoji: '🌶️', aliases: ['chili sauce'], per100: { cal: 93, protein: 2.0, carbs: 19.0 }, units: [{ name: 'tsp', grams: 7 }] },
  { id: 'sugar', name: 'Sugar', category: 'condiment', emoji: '🍬', aliases: ['white sugar', 'cane sugar'], per100: { cal: 387, protein: 0, carbs: 100.0 }, units: [{ name: 'tsp', grams: 4 }, { name: 'packet', grams: 4 }] },
  { id: 'teriyaki-sauce', name: 'Teriyaki sauce', category: 'condiment', emoji: '🍶', aliases: ['teriyaki'], per100: { cal: 89, protein: 5.9, carbs: 15.6 }, units: [{ name: 'tbsp', grams: 18 }] },
  { id: 'tomato-paste', name: 'Tomato paste', category: 'condiment', emoji: '🍅', per100: { cal: 82, protein: 4.3, carbs: 18.9 }, units: [{ name: 'tbsp', grams: 16 }] },
  { id: 'vinaigrette', name: 'Vinaigrette', category: 'condiment', emoji: '🥗', aliases: ['balsamic vinaigrette', 'italian dressing'], per100: { cal: 302, protein: 0.3, carbs: 6.0 }, units: [{ name: 'tbsp', grams: 15 }] },
]

export const INGREDIENT_BY_ID = new Map(INGREDIENT_LIBRARY.map(i => [i.id, i]))
